services:
  notifier:
    image: notifier
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./already_sent.pkl:/app/already_sent.pkl